### ISSUE TITLE
the memory increase..

### ISSUE THREAD

**Issue by liomessip** [Barbosik/MultiOgar#171] opened 2016-07-11 19:18 UTC
2gb of memory uses multiogar after a long time

how to fix..

**Comment by MastaCoder** [comment] 2016-07-11 21:17
turn off serverstats.

**Comment by liomessip** [comment] 2016-07-11 23:00
My server stats on -1 and have the same error

**Comment by Barbosik** [comment] 2016-07-12 00:40
Try to reduce food/virus/player count. Because each cell holds some small amount of memory. So, if you're using a lot of cells (a lot of food, a lot of viruses or a lot of players) it require more memory.

**Comment by SimonOrJ** [comment] 2016-07-13 01:44
I have stats disabled (running 1.2.34), but the memory leak is still there.

I'll report back after updating to the latest.

**Comment by Barbosik** [comment] 2016-07-13 02:49
@SimonOrJ: when you have memory leak on running server, try to execute sudo netstat -otup
And look for FIN_WAIT2 state for connections. Let me know if you have a lot of such connections.
These ghost connections may appears when the client doesn't close connection properly.

**Comment by SimonOrJ** [comment] 2016-07-13 03:47
Apparently, I cannot allocate memory when trying to use any command now...

**Comment by Barbosik** [comment] 2016-07-13 03:51
Probably your server is under DDoS attack from minion botters. Try to cleanup banlist and check if it helps.
I think there is need to enforce socket destroy to close connection as soon as possible

**Comment by Barbosik** [comment] 2016-07-13 04:33
Try to execute `sudo netstat -notp` and check for connections in FIN_WAIT2 state with disabled timer (timer=off). If any it means that there is memory leak related with connection which is not closed properly on client side

**Comment by retslac** [comment] 2016-07-13 16:44
@Barbosik I don't think the increasing memory has anything to do with socket connections not closing correctly on client side.  Now, i'm not using MultiOgar, but i think problem is the same as in other Ogar projects.

I think the increasing memory is actually caused by 2 (related) problems.  First one is that Ogar server just keeps on sending updatenodes packets to clients.  Even when some of those clients cannot keep up with reading from the socket buffer.  As a consequence socket buffers of very slow clients will keep on growing larger and larger causing every increasing memory consumption.

Second problem is that Ogar server doesn't clean up the connections correctly so all closed sockets will remain in memory forever.  This is caused by the socket cross-referencing in server.  Because of this, the garbage collector cannot detect nor release the memory of closed sockets.  To fix correct cleanup you could add below lines after removing disconnected players in PlayerTracker.js.  This should enable the gc to release the memory.
```
this.socket.packetHandler.socket = null;
this.socket.packetHandler = null;
this.socket.playerTracker = null;
this.socket = null;
```

I have a fix for first problem as well, which works good for me.  But i wanna see what solution you come up with because i really like your ideas and coding style...  :)

**Comment by NatsuTheGreat** [comment] 2016-07-13 16:59
I hope to see the first problem solved :P When I play on my private server, the client uses up 300 MB memory. With a map of 11180 x 11180, 1700 food cells, 1 player and 30 viruses.

**Comment by Barbosik** [comment] 2016-07-14 04:11
@retslac: 
1) Slow clients is really can grow memory usage. The vanilla server has the same issue. But vanilla doesn't break connection even if you stop receiving for several minutes :)

2) I don't think that cross referencing can leads to memory leaks. Because GC kills cross-referenced entries with no problem. But it will be killed when both instances will be released. 
So it will be released after playerDisconnectTime.

**Comment by SimonOrJ** [comment] 2016-07-14 04:15
The server's leaking RAM right now, but there's no mention of "FIN_WAIT2" or similar on the state.

**Comment by Barbosik** [comment] 2016-07-14 04:20
@SimonOrJ: can you check Quad node count with `debug` in server console?
If this value grows the same as `memory leak', then it's not memory leak. It's just condition when cells require more memory to be stored in the tree.

**Comment by Barbosik** [comment] 2016-07-14 04:24
Also there is a problem with some players. They players like to disconnect and connect again very often. It's bad for server performance, because they produce a lot of ghost connections which remains at least 1 minute.

**Comment by SimonOrJ** [comment] 2016-07-14 05:22
I run that from time to time.  It doesn't seem to increase dramatically.

```
Clients:          20 / 128 + bots
Total nodes:    1183
- Client cells:  245 / 1280
- Ejected cells:   8
- Foods:         880 / 1000
- Viruses:        50 / 200
Moving nodes:      0
Quad nodes:      901
Quad items:     1183
```

**Comment by Barbosik** [comment] 2016-07-14 05:32
hm, strange. I will check if there is some memory leak

**Comment by retslac** [comment] 2016-07-14 13:25
> 1) Slow clients is really can grow memory usage. The vanilla server has the same issue. But vanilla doesn't break connection even if you stop receiving for several minutes :)

Don't really know how vanilla server handles this.  But i do know that vanilla client starts skipping rendering cycles if it takes more than 240 ms between reading updatenodes packets.
My fix on serverside was not to close the connection of slow clients (as in original Ogar), but to skip sending updatenodes packets to client if the last 2 of those packets haven't been read yet by client.  You off course need to remain a copy of the last visible nodes sent to client for resuming later on.


> 2) I don't think that cross referencing can leads to memory leaks. Because GC kills cross-referenced entries with no problem. But it will be killed when both instances will be released. 
 So it will be released after playerDisconnectTime.

Are you sure of this?  I don't have a deep knowledge of node.js but according to my tests a couple of months ago, the memory of closed socket buffers never got released.  But after i added the 4 lines i mentioned above and did the same tests, memory usage dropped like a stone right after the gc kicked in.  It's been working without memory problems ever since.  I was using node 5.x at the time, might make a difference?

> The real problem with memory leak is related to socket behavior inside node.js sockets implementation. When it calls socket.end(), the operating system keeps socket until receive ACK from the remote client. So, if remote client doesn't send ACK on socket close it may leads to memory leaks in some case (there are some race conditions in node.js socket implementation). Because such connection for some conditions may remains forever in FIN_WAIT state.

Interesting.  Hope you find a good solution.

**Comment by Barbosik** [comment] 2016-07-14 15:40
@retslac: Don't really know how vanilla server handles this.

Vanilla server just enqueue all updates if the client stops to receive it. When the client resume receiving, vanilla server sends all enqueued updates with with maximum possible speed.

@retslac: Are you sure of this

yes, any managed language (with garbage collector) can handle cross referenced links with no problem.

**Comment by retslac** [comment] 2016-07-14 18:58
> Vanilla server just enqueue all updates if the client stops to receive it. When the client resume receiving, vanilla server sends all enqueued updates with with maximum possible speed.

I think this also depends on which browser client uses.  Some browsers like chrome seem to read socket buffers much faster and enqueue everything in browser.  You rarely see a queue on server side with chrome clients.  Firefox clients on the other hand seem to build up queue on server side much more.  Just something i noticed.

> If you skip some updates it will leads to jerky movement on the client with bad connection.
 But it will be good to add some threshold to kick the client with large queue

If client still has a queue when server wants to send next update packet, it means he's already having lag.  If server keeps on pushing packets onto that queue, it means even more lag for that client and more memory consumption for server.  I think in this case it's better to skip packets.  It does create a 'sudden move' update like you say.  But in reality this only happens once in a while and on exactly 1 frame, it's not like a constant on/off skipping of updates.  So it isn't really disturbing for client and in my view better than building bigger queue which leads to longer lasting lag for client.

> my server works with no memory leaks and I didn't changed anything in the code ;)

Yeah, i didn't have it at first either.  Not exactly sure why, but it seems to me that just some of the clients cause this.  But i guess server should be able to handle all of them.

**Comment by Barbosik** [comment] 2016-07-14 19:12
@retslac: I think this also depends on which browser client uses. Some browsers like chrome seem to read socket buffers much faster and enqueue everything in browser.

may be you're right. I didn't used browser. I used native application and stop it in the debugger. So entire all code was stoped. But may be it's enqueued in the network driver.

@retslac: If client still has a queue when server wants to send next update packet, it means he's already having lag. If server keeps on pushing packets onto that queue, it means even more lag for that client and more memory consumption for server. 

no, it will not leads to more lag if delay is not so high. Because server sends packets with 40 ms interval. So, if the client has a lag for 500-1000 ms (it may happens sometimes even with good connection). It will be flushed in the next 1-5 ms.

@retslac:  I think in this case it's better to skip packets. It does create a 'sudden move' update like you say. 

it's exactly how OgarUL works. And it's the reason why it works not smooth and with high jerky in movements.

**Comment by retslac** [comment] 2016-07-14 20:50
> no, it will not leads to more lag if delay is not so high. Because server sends packets with 40 ms interval. So, if the client has a lag for 500-1000 ms (it may happens sometimes even with good connection). It will be flushed in the next 1-5 ms.

Yeah, seems reasonable.  But i also noticed clients with queues building up really fast which never got flushed.

> But if you skip even 1 frame. It will leads to jerky movement on the client. And it will be very noticeable for the user. It will break smoothness.
> The secret of smooth movements is to NOT skip any frame.

I know it breaks smoothness for 1 frame.  But laggy clients don't have smooth movement anyway.  And i think it's just the same with a bigger queue.  Because when client reads the entire queue, it will only remember last received packet.  So, in effect, you could say client skips packets.  And if client doesn't read entire queue, it will lead to more lag.

> And I can say that if you will skip even 1 frame, it will leads to incorrect update for some cells. For example ejected mass or food may appears in the wrong place on the client screen. It's due to protocol optimizations. But if you remove this optimization it will leads to high lags due to high network load, because it will increase network traffic dramatically.

You're right.  You cannot just skip packets without storing extra info needed for resuming packets later on.  I had to change several things for it to work correctly.  But i also have different packet optimizations than MultiOgar, so not sure if this is really useable to you.  Anyways, it works for me, but i was never really happy with it.  Which is why i wanted to see if you could come up with something better... :)
I didn't like the original solution by Ogar either, which was to disconnect those clients immediately.


PS: Good luck on continuing your project.  Great work!!!  I'm truely amazed by the pace at which this is going...

**Comment by NatsuTheGreat** [comment] 2016-07-15 00:28
@retslac Sorry for interrupting, but are you available right now?

**Comment by Barbosik** [comment] 2016-07-15 12:40
it seems that out of memory issue solved. The root of cause - some bad guys who used mistake in the network code to crash the server. Now works great :)

**Closed by Barbosik** 2016-07-15 12:40 UTC
Labels: issue

**Comment by retslac** [comment] 2016-07-15 20:15
@NatsuTheGreat Hi Natsu, how you been

**Comment by NatsuTheGreat** [comment] 2016-07-15 20:32
@retslac Been very well. I am very excited to see you again!

**Comment by NatsuTheGreat** [comment] 2016-07-15 23:56
@retslac Are you there?

**Comment by retslac** [comment] 2016-07-16 00:26
I'm on discord
