### ISSUE TITLE
How to make macro like agar.io when tricksplited 16x for MultiOgar

### ISSUE THREAD

**Issue by NameYT** [Barbosik/MultiOgar#403] opened 2016-11-04 04:45 UTC
I already Changed ejectCooldown from -9999999 and still when i click Ex = 16 x it only split 8x
So what i'm about to do?

**Comment by cowpits** [comment] 2016-11-04 17:35
I have mine set to ejectCooldown = 1 and playerSpeed = 1.2
when splitting 16x using macro is very fast and ejecting mass using macro is like water. 
Try it on my server https://goo.gl/MKduPV

**Comment by Megabyte918** [comment] 2016-11-04 20:24
Duplicate of #389 and #399

**Comment by Jhair2015** [comment] 2016-11-05 00:22
@cowpits Could you help me create my server on ddns.net or the host you use? :)

Please!! :)

**Comment by NameYT** [comment] 2016-11-05 01:20
@Jhair2015 Try hosting at codeanywhere i have hosted my own server 📦

**Closed** 2016-11-05 07:01 UTC

**Comment by NatsuTheGreat** [comment] 2016-11-06 00:55
This guy exaggerates way too much.

**Comment by MastaCoder** [comment] 2016-11-10 23:29
> @Jhair2015 Try hosting at codeanywhere i have hosted my own server 📦

This is why good things never stay.
