### ISSUE TITLE
uws mod crash

### ISSUE THREAD

**Issue by David1ali12** [Barbosik/MultiOgar#190] opened 2016-07-14 02:18 UTC
```
[FATAL] TypeError: this.emit is not a function
    at Socket.WebSocket.sendPacket (/home/ubuntu/workspace/src/GameServer.js:1620:18)
    at PlayerTracker.sendUpdate (/home/ubuntu/workspace/src/PlayerTracker.js:395:17)
    at GameServer.updateClients (/home/ubuntu/workspace/src/GameServer.js:512:39)
    at GameServer.mainLoop (/home/ubuntu/workspace/src/GameServer.js:620:10)
    at Timer.listOnTimeout (timers.js:92:15)
```
I used uws is that effects ?
because uws was much faster
after 10 mins it crashes I cloned from henopied branch

**Comment by darknight99x** [comment] 2016-07-14 02:35
Yes this is the reason, uws is not supported.

**Comment by David1ali12** [comment] 2016-07-14 02:42
no it works but after 10 mins it crashes I cloned from henopied branch

**Comment by Barbosik** [comment] 2016-07-14 03:41
yes, uws is still not added, because there is need for a deep investigation for issues,
Default ws is more stable.

**Comment by henopied** [comment] 2016-07-14 15:52
I think I know the issue, that is in sendpacket we are trying to emit close event ourselves, either we should remove that or not use emit and change it to onclose.

**Comment by Barbosik** [comment] 2016-07-14 16:00
Closed, because duplicate of issue https://github.com/Barbosik/MultiOgar/issues/158

**Closed by Barbosik** 2016-07-14 16:00 UTC
Labels: mods

**Comment by henopied** [comment] 2016-07-14 17:46
Regardless that this is a duplicate it seems to have been fixed in the latest uws.
