### ISSUE TITLE
Mother Cell's in Experimental are infinitely tiny.

### ISSUE THREAD

**Issue by darknight99x** [Barbosik/MultiOgar#189] opened 2016-07-14 01:08 UTC
I don't think this happened before but after a recent update I believe, the mother cells are bugged.

**Comment by SimonOrJ** [comment] 2016-07-14 03:44
https://github.com/Barbosik/MultiOgar/blob/master/src/gamemodes/Experimental.js#L41

The "null" on the last argument may be the reason.  Try changing it to 149 for short-term solution.
`    var mother = new Entity.MotherCell(gameServer, null, pos, 149);`

Another problem I see is that the mother cells don't see enough food cell spawns, especially when playing alone or in small number.

**Comment by darknight99x** [comment] 2016-07-14 03:56
Thanks @SimonOrJ, I wish to see what @Barbosik says about it first. It's quite confusing, it was working before a recent update.

**Comment by Barbosik** [comment] 2016-07-14 04:53
you don't need to pass 149 size to MotherCell. Because it will use default size for null value. Default size for MotherCell is 149.

Actually this is not a bug. MotherCell stops to eject food when total food amount on the map reach `foodMaxAmount` value from gameserver.ini
It prevents lags for the server and clients. For example if MotherCell will eject 20000 foods, it will leads to extreme lags. You will gel very-very low fps on the client in such case. Also it will leads to server lags, because a lot of cells will be placed in the same location and it will need to process a lot of collisions.

**Comment by NatsuTheGreat** [comment] 2016-07-14 04:55
I am making a pull request to fit the agar.io mothercell behavior. It allows for mother cells to get big and be fed a lot. I understand about the lag, should I include a maxSize value too?

**Comment by NatsuTheGreat** [comment] 2016-07-14 04:56
I'll commit tomorrow, going to bed now.

**Comment by darknight99x** [comment] 2016-07-14 04:59
@Barbosik I don't think you understand.

Can you play experimental on your version of MultiOgar, then you'll see what i'm talking about?
MotherCell's are extremely small and broken.

**Comment by Barbosik** [comment] 2016-07-14 05:08
@darknight99x: ok, I will check

**Comment by Barbosik** [comment] 2016-07-14 05:12
Yeah, there is a bug with MotherCell, will be fixed soon

**Comment by darknight99x** [comment] 2016-07-14 05:13
Okay thanks @Barbosik 

Glad there is active development here.

**Comment by Barbosik** [comment] 2016-07-14 05:15
fixed

**Closed by Barbosik** 2016-07-14 05:15 UTC
Labels: bug
